# The URL the site will be built for
base_url = "https://KaranamGireesa-1.github.io/portfolio"

theme = "vonge"

title = "Gireesa's Portfolio"
author = "Karanam Gireesa"
description = "Portfolio site of Karanam Gireesa"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feeds = true
feed_filenames = ["atom.xml"]
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
logo_image = "/favicon.ico"
social_media_share_image = "/images/gireesa-picture.png"
disqus_identifier = ""
google_analytics = ""
twitter_handle = ""

author_image = '/images/gireesa-picture.png'

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/projects", title = "Projects" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "https://www.canva.com/design/DAGwCf3b0Kg/oXCf1wF5j49g5EUXmJNeDQ/edit?utm_content=DAGwCf3b0Kg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton", title = "CV ðŸ¡µ", external = true },
]
social_icons = [
    { url = "https://github.com/KaranamGireesa-1", icon = "GitHub" },
    { url = "https://www.linkedin.com/in/gireesakaranam/", icon = "LinkedIn" },
    { url = "$BASE_URL/atom.xml", icon = "RSS" },
]
date_format = "%d %b %Y"
language_direction = "auto"

[extra.footer]
menu = []

[[extra.content_blocks]]
block = "hero"
title = "Hi there, I am Gireesa Karanam"
description_html = "I am a <strong>Data Analyst</strong> and <strong>Business Analytics</strong> professional with an MBA in Business Analytics and hands-on experience working on real-world datasets across business, research, and digital transformation initiatives. Currently part of the <strong>Business Digital Organization</strong> at <strong>Bosch</strong>, I focus on turning raw, complex data into clear insights that support better decisions."
image = "/images/gireesa-picture.png"
image_alt = "Gireesa Karanam's picture"
cta_button_link = ""
cta_button = ""
works_button_link = "#projects"
works_button = "See my works"

[[extra.content_blocks]]
block = "projects-section"
title = "Latest Works"
description_html = """
    <p>I show only my best works built completely with passion, simplicity,
    and creativity!</p>"""
link_url = "https://KaranamGireesa-1.github.io/portfolio/projects"
show_projects = true
